default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "oroshi") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", "5432") %>

development:
  primary:
    <<: *default
    database: oroshi_sandbox_development
  queue:
    <<: *default
    database: oroshi_sandbox_development_queue
    migrations_paths: db/queue_migrate
  cache:
    <<: *default
    database: oroshi_sandbox_development_cache
    migrations_paths: db/cache_migrate
  cable:
    <<: *default
    database: oroshi_sandbox_development_cable
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: oroshi_sandbox_test
  queue:
    <<: *default
    database: oroshi_sandbox_test_queue
    migrations_paths: db/queue_migrate
  cache:
    <<: *default
    database: oroshi_sandbox_test_cache
    migrations_paths: db/cache_migrate
  cable:
    <<: *default
    database: oroshi_sandbox_test_cable
    migrations_paths: db/cable_migrate

production:
  primary:
    <<: *default
    database: oroshi_sandbox_production
  queue:
    <<: *default
    database: oroshi_sandbox_production_queue
    migrations_paths: db/queue_migrate
  cache:
    <<: *default
    database: oroshi_sandbox_production_cache
    migrations_paths: db/cache_migrate
  cable:
    <<: *default
    database: oroshi_sandbox_production_cable
    migrations_paths: db/cable_migrate
