test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google_active_storage:
  service: GCS
  project: <%= ENV["GCLOUD_PROJECT"] %>
  credentials: <%= ENV["GCLOUD_CREDENTIALS_PATH"] %>
  bucket: <%= ENV["GCLOUD_BUCKET"] %>
  public: true
